### ISSUE TITLE
No Nexus Found

### ISSUE THREAD

**Issue by alikhangholi** [phantasma-io/Spook#18]
Hello.
I am getting this error on ubuntu when I try to run a node in my computer:
"No Nexus Found."
This error is mentioned no where in the documnetation nor the google search. What is this error and how can I fix it?

**Comment by vincentgeneste** [comment]
Hi! Not sure which doc you're following but please use this one

https://docs.phantasma.io/

it should have all you need to get started, if not feel free to ask.

**Comment by alikhangholi** [comment]
@vincentgeneste Thank you for your answer.
I was able to run Phantasma node using Phantasma SDK, the SDK generates the Nexus, but i dont know how to generate it my self. can you help me with that?

**Comment by Relfos** [comment]
@alikhangholi   you need to setup nexus.bootstrap to true in order to generate a new nexus.

Check this config example
https://github.com/phantasma-io/Spook/blob/master/Spook/config_testnet.json#L25

Also best if you just copy that file contents into your own config.json, instead of making one from scratch

**Comment by alikhangholi** [comment]
Thanks for that. it worked for me and the genesis block generated.
but there is another error:
Unhandled exception. Phantasma.Domain.ChainException: add block @ main failed, reason: No support for oracle prices in this node
   at Phantasma.Simulator.NexusSimulator.EndBlock(Mempool mempool) in F:\Blockchain.Dev\Phantasma\PhantasmaChain\Phantasma.Simulator\NexusSimulator.cs:line 285
   at Phantasma.Simulator.NexusSimulator..ctor(Nexus nexus, PhantasmaKeys ownerKey, Int32 seed, Logger logger) in F:\Blockchain.Dev\Phantasma\PhantasmaChain\Phantasma.Simulator\NexusSimulator.cs:line 149
   at Phantasma.Spook.Spook.<>c__DisplayClass54_0.<StartSimulator>b__0() in F:\Blockchain.Dev\Phantasma\Spook\Spook\Spook.cs:line 192
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Relfos** [comment]
You are missing the cryptocompare API key, get one here:
https://min-api.cryptocompare.com/

**Comment by alikhangholi** [comment]
Thank you @Relfos, the node is running now.
just a question: What does the crymptocompare API do with this blockchain? Does the Phantasma blockchain depends on it? or can it be deleted safely?

**Comment by Relfos** [comment]
It is used as data source for the on-chain price oracles. Soon we will add support for more sources
