### ISSUE TITLE
Error trying to run Spook 1.6.1 release

### ISSUE THREAD

**Issue by FrostyFitz** [phantasma-io/Spook#22]
I downloaded the 1.6.1 release of Spook and I am trying to run it. I have a config.json that is set up for testnet. When I run spook in the cli it throws the following error:
System.Exception: Unconfigured setting: crypto.compare.key
   at Phantasma.Core.Utils.Arguments.GetString(String key, String defaultVal, Boolean required) in C:\Code\PhantasmaChain\Phantasma.Core\Utils\ArgumentParser.cs:line 108
   at Phantasma.Spook.OracleSettings..ctor(NodeMode nodeMode, Arguments settings, DataNode section) in C:\Code\Spook\Spook\Settings.cs:line 405
   at Phantasma.Spook.SpookSettings..ctor(String[] args) in C:\Code\Spook\Spook\Settings.cs:line 59
There were issues loading settings from config.json, aborting...

**Comment by tritao** [comment]
Check the README, you need to setup your CryptoCompare API key in the config.
